
new-app:
	cargo leptos new -g leptos-rs/start-axum -n app 
	curl -o Dockerfile https://raw.githubusercontent.com/maximilianou/weekly70/refs/heads/main/web38-docker/Dockerfile

del-app:
	rm -r app
	rm Dockerfile