[package]
name = "web25_actions"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-timers = { version = "0.3.0", features = ["futures"] }
leptos = { version = "0.6.15", features = ["csr", "nightly"] }
uuid = { version = "1.11.0", features = ["v4"] }
